[mcp_servers.mis-admin]
command = 'C:\Users\isuru\AppData\Roaming\Python\Python313\Scripts\context.exe'
args = [
    "mcp",
    'd:\MIS\mis-admin',
]

[mcp_servers.mis-admin.env]
PYTHONUTF8 = "1"
HF_HUB_DISABLE_SYMLINKS_WARNING = "1"

[mcp_servers.mis-backend]
command = 'C:\Users\isuru\AppData\Roaming\Python\Python313\Scripts\context.exe'
args = [
    "mcp",
    'd:\MIS\mis-backend',
]

[mcp_servers.mis-backend.env]
PYTHONUTF8 = "1"
HF_HUB_DISABLE_SYMLINKS_WARNING = "1"
